cc_test(
  name = "inverted_multi_index_test",
  srcs = [
    "inverted_multi_index_test.cpp",
  ],
  deps = [
    "@gtest//:gtest",
    "//external:gflags",
    "//similia/proto",
    "//similia/utils:inverted_multi_index",
  ],
  linkopts = [
    "-lglog",
  ],
)
